"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sf1L9kpOCDixtquZKqCTMmwW4Z3YJ7Bf
"""

#Name: Long Hoang
#Lab 2

import random

"""#Task 1

This program will perform input/output dialog for apple purchase
"""

print("Task 1")

numApples = int(input("How many apples you have bought? "))
price = float(input(f"How much do you pay for {numApples} apple? "))
print(f"In average, each apple costs ${round(price / numApples, 2)}") #calculate the average price and round it for proper format

#use random integer as number of children, between 2 and number of apples
numChildren = random.randint(2, numApples)
appleForChild = int(numApples / numChildren) #calculate how many apples for each child, whole number only
leftOver = numApples % numChildren #calculate the remainder

print(f"There are {numChildren} children here, so each could get {appleForChild} {'apple' if appleForChild < 2 else 'apples'} with {leftOver} {'apple' if leftOver < 2 else 'apples'} leftover")

#{'apple' if appleForChild < 2 else 'apples'} --> for proper format, singular and plural words
#{'apple' if leftOver < 2 else 'apples'}

print("Thank you for shopping!")

# output task 1

'''
Because the number of children is generated randomly, so the first test won't be 100% the same as the sample output!

How many apples you have bought? 13
How much do you pay for 13 apple? 5.27
In average, each apple costs $0.41
There are 2 children here, so each could get 6 apples with 1 apple leftover
Thank you for shopping!
'''

'''
How many apples you have bought? 10
How much do you pay for 10 apple? 20.29
In average, each apple costs $2.03
There are 3 children here, so each could get 3 apples with 1 apple leftover
Thank you for shopping!
'''

'''
How many apples you have bought? 2
How much do you pay for 2 apple? 5.69
In average, each apple costs $2.85
There are 2 children here, so each could get 1 apple with 0 apple leftover
Thank you for shopping!
'''

"""#Task 2

This program will compute and display the FV (future value)
given PV (present value), INT (interest rate), and YRS (years) as input
"""

print("\nTask 2")

pv = float(input("What is the present value? "))
rate = float(input("What is the interest rate? "))
yrs = int(input("How many years for the deposit? "))

fv = pv * (1 + rate / 100) ** yrs #calculate using the formula
print(f"The future value is ${round(fv, 2)}, assuming you deposit ${int(pv) if pv.is_integer() else pv} today with an interest rate of {int(rate) if rate.is_integer() else rate}% for {yrs} years")

#int(pv) if pv.is_integer() else pv --> proper format. since pv is float, wholen number can be 100.00 --> change that to 100
#int(rate) if rate.is_integer() else rate

# output task 2
'''
What is the present value? 1000
What is the interest rate? 5
How many years for the deposit? 10
The future value is $1628.89, assuming you deposit $1000 today with an interest rate of 5% for 10 years
'''

'''
What is the present value? 2549.60
What is the interest rate? 3.4
How many years for the deposit? 30
The future value is $6951.66, assuming you deposit $2549.6 today with an interest rate of 3.4% for 30 years
'''

'''
What is the present value? 11300
What is the interest rate? 5
How many years for the deposit? 25
The future value is $38265.81, assuming you deposit $11300 today with an interest rate of 5% for 25 years
'''

"""#Task 3

This program will use three assignment statements (highlighted) to swaps two values
"""

print("\nTask 3")

x = float(input("Enter the first number: "))
y = float(input("Enter the second number: "))

print("Before swapping: ", x, y)
# temp = x
# x = y
# y = temp
x, y = y, x #perform swap
print ("After swapping: ", x, y)

# output task 3

'''
Enter the first number: 2
Enter the second number: 3
Before swapping:  2.0 3.0
After swapping:  3.0 2.0
'''

'''
Enter the first number: 2.6
Enter the second number: 3.5
Before swapping:  2.6 3.5
After swapping:  3.5 2.6
'''

"""#Task 4

This program will prompt user to enter two strings and print statements with the first one printing out the concatenation
of two strings while the second one printing out the first string three times
"""

print("\nTask 4")

first = input("Enter the first string: ")
second = input("Enter the second string: ")
print(f"Concatenation of 2 strings: {first + second}")
print(f"First string 3 times: {first * 3}")

# output task 4

'''
Enter the first string: good
Enter the second string: morning
Concatenation of 2 strings: goodmorning
First string 3 times: goodgoodgood
'''

'''
Enter the first string: hello
Enter the second string: world
Concatenation of 2 strings: helloworld
First string 3 times: hellohellohello
'''