# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qivw_4hVN4KUR4HjQVt0arqcqvmPmfUn
"""

#Name: Long Hoang
#Lab 3

import random

"""#Task 1

"""

print("Task 1\n")

"""This program will simulate rock, paper, scissors game"""

play = True

while play:
  #computer generates random choice
  cmpChoice = random.choice(["rock", "paper", "scissors"])

  #ask user for their choice
  userChoice = input("Enter your choice, rock, paper or scissors: ")

  #if invalid input, reprompt
  while userChoice not in ["rock", "paper", "scissors"]:
    userChoice = input("Enter your choice exactly as one of the given choices: rock, paper or scissors. ")

  # win/lose/tie output phrase to avoid code repitition
  tie = f"User choice: {userChoice} = Computer choice: {cmpChoice}"
  win = f"User choice: {userChoice} > Computer choice: {cmpChoice}"
  lose = f"User choice: {userChoice} < Computer choice: {cmpChoice}"

  if userChoice == cmpChoice: #if tie
    print("It's a tie!")
    print(tie)

  elif userChoice == "rock" and cmpChoice == "scissors": #rock beats scissors --> user won
    print("You win!")
    print(win)

  elif userChoice == "paper" and cmpChoice == "rock": #paper beats rock --> user won
    print("You win!")
    print(win)

  elif userChoice == "scissors" and cmpChoice == "paper": #scissors beats paper --> user won
    print("You win!")
    print(win)

  else: #all other cases: user lost
    print("You lose!")
    print(lose)

  #ask if user wants to continue playing
  more = input("\nDo you want to play again? (y/n): ")

  #if invalid input
  while more not in ["y", "n", "yes", "no"]:
    more = input("Invalid input! Do you want to play again? (y/n): ")

  if more == "n" or more == "no": #user doesn't want to continue
    print("Game quit!")
    play = False
    break
  elif more == "y" or more == "yes": #user wants to continue --> continue the loop
    pass

# output task 1: include 7 test game play including some invalid input case (handle exceptions from the user)

'''
Enter your choice, rock, paper or scissors: rock
It's a tie!
User choice: rock = Computer choice: rock

Do you want to play again? (y/n): y
Enter your choice, rock, paper or scissors: rock
You lose!
User choice: rock < Computer choice: paper

Do you want to play again? (y/n): y
Enter your choice, rock, paper or scissors: paper
You lose!
User choice: paper < Computer choice: scissors

Do you want to play again? (y/n): y
Enter your choice, rock, paper or scissors: rock
You win!
User choice: rock > Computer choice: scissors

Do you want to play again? (y/n): y
Enter your choice, rock, paper or scissors: scissors
You lose!
User choice: scissors < Computer choice: rock

Do you want to play again? (y/n): u
Invalid input! Do you want to play again? (y/n): y
Enter your choice, rock, paper or scissors: paper
It's a tie!
User choice: paper = Computer choice: paper

Do you want to play again? (y/n): yes
Enter your choice, rock, paper or scissors: paper
It's a tie!
User choice: paper = Computer choice: paper

Do you want to play again? (y/n): n
Game quit!
'''

"""#Task 2

"""

print("\nTask 2")

"""This program will convert the following if-else statement and print statements into one print statement with a conditional expression as an argument of the print statement."""

count = int(input("Please enter the number of items purchased: "))
total = int(input("Please enter the total cost: "))

#conditional expression for the if-else statement below
print(f"Average = {'0' if count == 0 else round(total/count, 2)}")
#although not mention in the lab, I thought it would be nicce to follow the proper dollar format (round to 2 digits after the decimal) like in previous labs


# if count == 0 :
#   average = 0
# else :
#   average = total/count

# output task 2

'''
Please enter the number of items purchased: 13
Please enter the total cost: 35
Average = 2.69
'''

'''
Please enter the number of items purchased: 0
Please enter the total cost: 5
Average = 0
'''

'''
Please enter the number of items purchased: 20
Please enter the total cost: 29
Average = 1.45
'''

"""#Task 3"""

print("\nTask 3")

"""This program will convert the following Java/C++ like loop to Python"""

for j in range(1, 50, 2): # j going from 1 to 50 with a step of 2, because of 2 j++'s in the original for loop
    print(j, end=" ")

# output task 3

'''
1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
'''

"""#Task 4

"""

print("\n\nTask 4")

"""This program will use for-loop to perform a linear search"""

letters = "abcdefghijklmnopqrstuvwxyz"
seed = random.choice(letters) # a letter randomly generated by the computer

sentence = input("Enter a sentence: ")

print(f"Randomly generated seed letter: {seed}")

for letter in sentence:
  if letter == seed: #if found
    print("Found the randomly generated seed letter in the sentence!")
    break
else: #if not found (no break was executed)
  print("Not found the the randomly generated seed letter in the sentence!")

# output task 4: including found case and not found case

'''
Enter a sentence: abcdefghijklmnopqrstuvwxyz
Randomly generated seed letter: m
Found the randomly generated seed letter in the sentence!
'''

'''
Enter a sentence: hello
Randomly generated seed letter: t
Not found the the randomly generated seed letter in the sentence!
'''

'''
Enter a sentence: allez allez
Randomly generated seed letter: x
Not found the the randomly generated seed letter in the sentence!
'''

'''
Enter a sentence: carlos alcaraz going to wimbledon 2024 finale on Sunday
Randomly generated seed letter: w
Found the randomly generated seed letter in the sentence!
'''