#Name: Long Hoang 
#Test 1, question 30
"""test1.ipynb
Automatically generated by Colab.
"""

def calculate_tax(income):
  tax_due = 0
  # from the table, classify rates
  if income <= 9325:
      tax_due = income * 0.10 #(10%)
  elif income <= 37950:
      tax_due = 932.50 + (income - 9325) * 0.15 # $932.50 plus 15% of the excess over $9,325
  else:
      tax_due = 5226.25 + (income - 37950) * 0.25 # $5,226.25 plus 25% of the excess over $37,950

  after_tax_income = income - tax_due

  return tax_due, after_tax_income

def task1():
  #ask for input
  income = float(input("Enter taxable income for the year: "))

  tax_due, after_tax_income = calculate_tax(income)

  # round for proper dollar format
  print(f"Taxable Income: ${round(income, 2)}")
  print(f"Tax Due: ${round(tax_due, 2)}")
  print(f"After-Tax Income: ${round(after_tax_income, 2)}")

def calculate_result(n): #calculate the result = 2^2 + 3^2 + ... + n^2 + (n+1)^2
  total = 0
  for i in range(2, n + 2): #(2 -> n+1)
      total += i ** 2
  return total

def task2():
  while True:
    n = int(input("Enter a positive integer (or zero/negative to exit): "))

    #if 0 or negative number, terminate loop
    if n <= 0:
        break

    # calculate result
    result = calculate_result(n)

    print(f"The result for n = {n} is: {result}")

def f(x=1, y=5):
    return x**2 + y**3 #x^2 + y^3

def main():
  result1 = f()
  print("Result of f() (default parameters):", result1)

  result2 = f(y=1, x=5)
  print("Result of f(y=1, x=5):", result2)

  # ask user for input
  x = float(input("Enter value for x: "))
  y = float(input("Enter value for y: "))
  result3 = f(x, y)
  print(f"Result of f({x}, {y}) (user input): {result3}")

def exam1():
  print("Task 1\n")
  task1()

  print("\nTask 2\n")
  task2()

  print("\nTask 3\n")
  main()

#I intended to make all the code into main, but because task 3 has the main, so I made a exam1() function and call it (just like what we did in the hw) hope this's ok
exam1()

#output task 1
'''
Enter taxable income for the year: 8000
Taxable Income: $8000.0
Tax Due: $800.0
After-Tax Income: $7200.0
'''

'''
Enter taxable income for the year: 20050
Taxable Income: $20050.0
Tax Due: $2541.25
After-Tax Income: $17508.75
'''

'''
Enter taxable income for the year: 56000
Taxable Income: $56000.0
Tax Due: $9738.75
After-Tax Income: $46261.25
'''

#output task 2

'''
Enter a positive integer (or zero/negative to exit): 10
The result for n = 10 is: 505
Enter a positive integer (or zero/negative to exit): 25
The result for n = 25 is: 6200
Enter a positive integer (or zero/negative to exit): -1
'''

# output task 3

'''
Result of f() (default parameters): 126
Result of f(y=1, x=5): 26
Enter value for x: 2
Enter value for y: 3
Result of f(2.0, 3.0) (user input): 31.0
'''